#!/usr/bin/env python3
"""生成 tests/inflate_vectors.h —— DEFLATE 解压矢量（确定性，可重复生成）。

每条用例只记录**明文长度 + FNV-1a 指纹**，而不是明文本身：大用例的明文动辄
几十 KB，写进头文件会让源码膨胀到没有意义的体积，而长度 + 32 位指纹足以锁住
「逐字节一致」这个判据（C 侧算同样的 FNV-1a）。

三种包装各生成一份：gzip / zlib / raw deflate —— 三者头尾相异，是三种独立的
代码路径（gzip 还要跳过 FNAME 段，Python 的 GzipFile 会写 FNAME，正好覆盖）。

用法：python3 tests/gen_inflate_vectors.py > tests/inflate_vectors.h
"""
import gzip
import io
import random
import sys
import zlib


def fnv1a(data: bytes) -> int:
    h = 0x811C9DC5
    for b in data:
        h = ((h ^ b) * 0x01000193) & 0xFFFFFFFF
    return h


def gzip_wrap(data: bytes, name: str) -> bytes:
    buf = io.BytesIO()
    with gzip.GzipFile(fileobj=buf, mode="wb", filename=name, mtime=0) as f:
        f.write(data)
    return buf.getvalue()


def gzip_wrap_extended(data: bytes, name: str) -> bytes:
    """手工构造带 FEXTRA + FNAME + FHCRC 的 gzip 成员。

    为什么要手工：Python 的 GzipFile 写不出 FEXTRA / FHCRC，而这两段正是
    包装解析里最容易数错偏移的地方（跳过 EXTRA 要按小端读长度，FHCRC 还要
    再加 2 字节）—— 不覆盖就等于这段代码没测过。
    """
    extra = b"NE\x02\x00xy"                       # 6 字节载荷
    flg = 0x04 | 0x08 | 0x02                      # FEXTRA | FNAME | FHCRC
    head = bytes([0x1F, 0x8B, 8, flg, 0, 0, 0, 0, 0, 0xFF])
    body = (head + len(extra).to_bytes(2, "little") + extra
            + name.encode() + b"\x00")
    hcrc = zlib.crc32(body) & 0xFFFF
    trailer = ((zlib.crc32(data) & 0xFFFFFFFF).to_bytes(4, "little")
               + (len(data) & 0xFFFFFFFF).to_bytes(4, "little"))
    return body + hcrc.to_bytes(2, "little") + raw_wrap(data) + trailer


def zlib_wrap(data: bytes) -> bytes:
    return zlib.compress(data, 9)


def raw_wrap(data: bytes) -> bytes:
    c = zlib.compressobj(9, zlib.DEFLATED, -15)
    return c.compress(data) + c.flush()


def build_cases():
    rnd = random.Random(7)                      # 固定种子 → 可重复生成

    cases = []

    # 1. 真实形状的小 JSON（最短路径：单个 dynamic 块）
    cases.append(("json_small", b'{"code":200,"result":{"songs":[1,2,3]}}'))

    # 2. 空明文（合法输入：三种包装都要能解出 0 字节）
    cases.append(("empty", b""))

    # 3. UTF-8 多字节（中文歌名/歌词的形状）
    cases.append(("utf8", "{\"code\":200,\"name\":\"起风了 — 买辣椒也用券\"}".encode("utf-8")))

    # 4. 自重叠回溯：5000 个 'A'，距离码 1 长度码 258 反复 —— 复制实现写错
    #    （用 memcpy 而不逐字节推进）在这里必崩
    cases.append(("run_a", b"A" * 5000))

    # 5. 不可压缩的随机二进制：压缩器会退化成 stored 块
    cases.append(("random_stored", bytes(rnd.getrandbits(8) for _ in range(2000))))

    # 6. 大输入 + 远距离回溯：循环模式 100 KB，跨多个块
    pattern = bytes(range(256)) * 400
    cases.append(("big_pattern", pattern))

    # 7. 高压缩比的大 JSON：重复的字段名（真实 playlist 响应的形状）
    item = ('{"id":%d,"name":"歌曲%d","ar":[{"id":1,"name":"歌手"}],'
            '"al":{"id":2,"name":"专辑"},"dt":240000,"fee":0},')
    big = "".join(item % (i, i) for i in range(400))
    cases.append(("json_big", ("[" + big + "]").encode("utf-8")))

    # 8. 全 NUL（位流里 0 密度极高，容易把 LSB-first 读反）
    cases.append(("nul_run", b"\x00" * 1000))

    return cases


def emit_array(out, cname: str, data: bytes):
    out.write("static const unsigned char %s[] = {" % cname)
    if not data:
        out.write("0")
    for i, b in enumerate(data):
        if i % 16 == 0:
            out.write("\n    ")
        out.write("0x%02x," % b)
    out.write("\n};\n")


def main():
    cases = build_cases()
    out = sys.stdout
    out.write("/* generated by tests/gen_inflate_vectors.py — do not edit */\n")
    out.write("#ifndef NE_INFLATE_VECTORS_H\n#define NE_INFLATE_VECTORS_H\n\n")

    for i, (name, plain) in enumerate(cases):
        # 奇数号走「带 FEXTRA/FHCRC 的扩展头」——把两套头解析路径都覆盖到
        gz = (gzip_wrap_extended if i % 2 else gzip_wrap)(plain, "%s.txt" % name)
        emit_array(out, "v%d_gz" % i, gz)
        emit_array(out, "v%d_zl" % i, zlib_wrap(plain))
        emit_array(out, "v%d_raw" % i, raw_wrap(plain))
        out.write("\n")

    out.write("typedef struct {\n"
              "    const char          *name;\n"
              "    size_t               plain_len;   /* 期望明文长度 */\n"
              "    unsigned             plain_sum;   /* 期望明文的 FNV-1a 32 */\n"
              "    const unsigned char *gz;   size_t gz_len;\n"
              "    const unsigned char *zl;   size_t zl_len;\n"
              "    const unsigned char *raw;  size_t raw_len;\n"
              "} inflate_vector;\n\n")

    out.write("static const inflate_vector inflate_vectors[] = {\n")
    for i, (name, plain) in enumerate(cases):
        out.write('    { "%s", %d, 0x%08xu, v%d_gz, sizeof v%d_gz, '
                  "v%d_zl, sizeof v%d_zl, v%d_raw, sizeof v%d_raw },\n"
                  % (name, len(plain), fnv1a(plain), i, i, i, i, i, i))
    out.write("};\n\n")
    out.write("#define INFLATE_VECTOR_COUNT "
              "(sizeof inflate_vectors / sizeof inflate_vectors[0])\n\n")
    out.write("#endif\n")


if __name__ == "__main__":
    main()
